
services:
  web:
    image: dunglas/frankenphp:latest
    container_name: frankenphp
    environment:
      - FRANKENPHP_CONFIG="worker ./public/index.php"
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ${PWD}:/app
